---
abstract: 'Template Renderer Plugin for Mojolicious'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0.94'
  perl: v5.10.0
configure_requires:
  Module::Build: '0.28'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-TtRenderer
no_index:
  directory:
    - example
recommends:
  EV: '0'
requires:
  Mojolicious: '3.33'
  POSIX: '0'
  Template: '2.18'
  Template::Provider: '0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/Mojolicious-Plugin-TtRenderer/issues
  homepage: http://perl.wdlabs.com/Mojolicious-Plugin-TtRenderer
  repository: git://github.com/plicease/Mojolicious-Plugin-TtRenderer.git
version: '1.54'
