---
abstract: 'Template Renderer Plugin for Mojolicious'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Mojo::IOLoop: '0'
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
  Test::More: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-TtRenderer
no_index:
  directory:
    - example
recommends:
  EV: '0'
requires:
  Carp: '0'
  Cwd: '0'
  File::Spec: '0'
  Mojo::Base: '0'
  Mojo::ByteStream: '0'
  Mojolicious: '3.33'
  Mojolicious::Plugin: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Template: '2.18'
  Template::Provider: '0'
  base: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/plicease/mojox-renderer-tt/issues
  homepage: http://perl.wdlabs.com/Mojolicious-Plugin-TtRenderer/
  repository: git://github.com/plicease/mojox-renderer-tt.git
version: '1.51'
