---
abstract: 'Template Renderer Plugin'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-TtRenderer
requires:
  Mojolicious: 3.33
  Template: 2.18
  perl: v5.10.0
resources:
  bugtracker: https://github.com/abh/mojox-renderer-tt/issues
  homepage: http://search.cpan.org/dist/Mojolicious-Plugin-TtRenderer/
  repository: git://github.com/abh/mojox-renderer-tt.git
version: 1.32
